/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CircleButton: typeof import('./src/components/buttons/circleButton.vue')['default']
    CloseButton: typeof import('./src/components/buttons/closeButton.vue')['default']
    Drawer: typeof import('primevue/drawer')['default']
    FloatLabel: typeof import('primevue/floatlabel')['default']
    IconButton: typeof import('./src/components/buttons/iconButton.vue')['default']
    InputText: typeof import('primevue/inputtext')['default']
    Password: typeof import('primevue/password')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TextButton: typeof import('./src/components/buttons/textButton.vue')['default']
    TTDrawer: typeof import('./src/components/TTDrawer.vue')['default']
    TTTextInput: typeof import('./src/components/TTTextInput.vue')['default']
  }
}
