/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    DatePicker: typeof import('primevue/datepicker')['default']
    Drawer: typeof import('primevue/drawer')['default']
    FloatLabel: typeof import('primevue/floatlabel')['default']
    InputNumber: typeof import('primevue/inputnumber')['default']
    InputText: typeof import('primevue/inputtext')['default']
    Password: typeof import('primevue/password')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectButton: typeof import('primevue/selectbutton')['default']
    Skeleton: typeof import('primevue/skeleton')['default']
    Toast: typeof import('primevue/toast')['default']
    TTAutoComplete: typeof import('./src/components/forms/TTAutoComplete.vue')['default']
    TTDatePicker: typeof import('./src/components/forms/TTDatePicker.vue')['default']
    TTDivider: typeof import('./src/components/misc/TTDivider.vue')['default']
    TTDrawer: typeof import('./src/components/misc/TTDrawer.vue')['default']
    TTIconButton: typeof import('./src/components/buttons/TTIconButton.vue')['default']
    TTNumberInput: typeof import('./src/components/forms/TTNumberInput.vue')['default']
    TTSelectButton: typeof import('./src/components/buttons/TTSelectButton.vue')['default']
    TTTextButton: typeof import('./src/components/buttons/TTTextButton.vue')['default']
    TTTextInput: typeof import('./src/components/forms/TTTextInput.vue')['default']
    TTToast: typeof import('./src/components/misc/TTToast.vue')['default']
  }
}
